language: go
before_install:
    - sudo add-apt-repository -y ppa:ceph-ubuntu/dev
    - sudo apt-get update
    - sudo apt-get install libleveldb-dev
install:
    - go get github.com/peterbourgon/diskv
    - go get github.com/jmhodges/levigo_leveldb_1.4
    - go get github.com/voxelbrain/goptions
    - go get github.com/feyeleanor/atomiser
    - go get github.com/syndtr/goleveldb/leveldb
    - go get code.google.com/p/snappy-go/snappy
    - go get github.com/akrennmair/epos
after_script:
    - go test -bench='.*'
