language: go
install:
    - go get github.com/peterbourgon/diskv
    - go get github.com/jmhodges/levigo_leveldb_1.4
    - go get github.com/voxelbrain/goptions
    - go get github.com/feyeleanor/atomiser
after_script:
    - go test -bench='.*'
